### PR TITLE
Added fix for detecting Edge version, (re-raise)

### LINKED ISSUE #422: Newer Edge versions not detected
Agent strings with "edg/", returns version 0.0.0.0

Note:
I have made a fork and a fix, and extended the tests to guard against this issue. Expect PR soon

### PR DESCRIPTION
**Pull request by frankhaugen**
Fixes #422

Replaces "edg" with "edge" on version detection if browser is edge.

Extended unit tests to encompass versions for Edge, including Chromium based versions

Related #360

(This was re-raised after realizing that the last PR was from the primary branch)

### CODE REVIEW

**Comment by wangkanai** [comment]
Have you change something that cause this test fail?

**Comment by frankhaugen** [comment]
No changes, but there is obviously something that someone has missed before, because the asserts are for transient services and the registration is scoped. It seems Dmytro changed the lifetimes and didn't update the unit tests:
image

I use LiveUnitTesting so I didn't run any solution-wide tests because it limits to the files one is working on, so if they passed or not before I added these changes, I don't know.

Suggest you run tests on PR-builds to prevent failing tests to be added in the future

**Comment by frankhaugen** [comment]
@wangkanai This is where the change happened: https://github.com/wangkanai/Detection/pull/369/files

**Review by wangkanai — COMMENTED** [review]
> Suggest you run tests on PR-builds to prevent failing tests to be added in the future

I pretty sure that I have CI with AppVeyor to check before every PR merged. Well, I will recheck again about this issue.

**Comment by wangkanai** [comment]
> @wangkanai This is where the change happened: https://github.com/wangkanai/Detection/pull/369/files

Thank you for helping identifying where this fail test originated from. I will recheck again regarding the transient or scope.

**Comment by wangkanai** [comment]
> > Suggest you run tests on PR-builds to prevent failing tests to be added in the future
> 
> I pretty sure that I have CI with AppVeyor to check before every PR merged. Well, I will recheck again about this issue.

I have made sure that test have all pass before merging into the main branch with PR #431

**Comment by wangkanai** [comment]
I think you will be have to rebase or merge your branch before. Because I have made a lot fixes.

**Comment by wangkanai** [comment]
@frankhaugen What do you think about my changes? any good.

**Comment by frankhaugen** [comment]
@wangkanai Nothing wrong with your changes. I like that you took my changes and improved upon them

**Comment by wangkanai** [comment]
Great! Lets merge this baby.

**Pull request merged**
