### PR TITLE
.NET standard 2.1 

### PR DESCRIPTION
**Pull request by wangkanai**
Reference #427

### CODE REVIEW

**Comment by wangkanai** [comment]
@frankhaugen I didn't think my library is able to change to `netstandard2.1` that easy.  I have problem with framework reference:

Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(283, 5): [NETSDK1073] The FrameworkReference 'Microsoft.AspNetCore.App' was not recognized.

`Microsoft.AspNetCore.App` seem to only like `netcoreapp3.0`.  I did some research about this and [find that its by design](https://github.com/dotnet/standard/issues/1671).

Try to see if you can make it work.

**Comment by frankhaugen** [comment]
@wangkanai if you don't use framework reference and reference the Nugets, you can. However I am unable to get the "AddRazorPages()" from the mvc.razor Nuget. It's possible that it's not possible to have the razor related parts in a standard library. I haven't had time to look at it other than the just removing the framework reference and going through and finding the Nugets needed

**Comment by wangkanai** [comment]
@frankhaugen yes, Detection has a lot dependency to the asp.net core base code into order function. Its was build ground up that way by design and a single project. NuGet require me to sign package before publishing to NuGet.

**Comment by wangkanai** [comment]
Will work on this on later date. if the issue is still relevance with .NET 5.0 release.

**Pull request closed without merging**
